import type { Metadata } from 'next'
import './globals.scss'
import Header from '@/components/Header/Header'
import { ThemeProvider } from '@/context/themeContext'

export const metadata: Metadata = {
  title: 'REST Countries API ',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang='en' data-theme='light'>
      <body>
        <ThemeProvider>
          <Header />
          {children}
        </ThemeProvider>
      </body>
    </html>
  )
}
