import type { Metadata } from 'next'
import './globals.scss'
import Header from '@/components/Header/Header'

export const metadata: Metadata = {
  title: 'REST Countries API ',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang='en'>
      <body>
        <Header />
        {children}
      </body>
    </html>
  )
}
